---
title: "P8105_hw2_tp2859"
output: html_document
date: "2024-10-01"
---

```{r}
library(tidyverse)
transit_data <- read.csv("NYC_Transit_Subway_Entrance_And_Exit_Data.csv")
```

```{r}
transit_clean <- transit_data %>%
  select(Line, Station.Name, Station.Latitude, Station.Longitude, Route1:Route11, 
         Entrance.Type, Entry, Vending, ADA)
transit_clean <- transit_clean %>%
  mutate(Entry = ifelse(Entry == "YES", TRUE, FALSE))
```




##a. How many distinct stations are there? 
```{r}
distinct_stations <- transit_clean %>%
  distinct(Line, Station.Name) %>%
  nrow()

distinct_stations
```

##b. How many stations are ADA-compliant?
```{r}
ada_compliant <- transit_clean %>%
  filter(ADA == "TRUE") %>%
  distinct(Line, Station.Name) %>%
  nrow()

ada_compliant
```
##b. How many stations are ADA-compliant?
```{r}
ada_compliant <- transit_clean %>%
  filter(ADA == "TRUE") %>%
  distinct(Line, Station.Name) %>%
  nrow()

ada_compliant
```

##c.What proportion of station entrances / exits without vending allow entrance?
```{r}
entry_withoutvending <- transit_clean %>%
  filter(Vending == "NO", Entry == TRUE) %>%
  nrow()
total_withoutvending <- transit_clean %>%
  filter(Vending == "NO") %>%
  nrow()
proportion_withoutvending <-entry_withoutvending/total_withoutvending
proportion_withoutvending
```
##reformat
```{r}
transit_clean <- transit_clean %>%
  mutate(across(Route1:Route11, as.character))

transit_clean_re <- transit_clean %>%
  pivot_longer(cols = Route1:Route11, names_to = "Route_Number", values_to = "Route") %>%
  filter(!is.na(Route))
#distinct stations serve the A train
The_A_train_stations <- transit_clean_re %>%
  filter(Route == "A") %>%
  distinct(Line, Station.Name) %>%
  nrow()

add_compliant_A <- transit_clean_re %>%
  filter(Route == "A",ADA == "TRUE") %>%
  distinct(Line, Station.Name) %>%
  nrow()

add_compliant_A
mlb11_df = read_excel("data/mlb11.xlsx", n_max = 20)
```




